source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem "rails"
gem "sprockets-rails"
gem "sqlite3"
gem "puma"
gem "importmap-rails"
gem "bootsnap", require: false

group :development, :test do
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
end

group :test do
  gem "capybara"
  gem "selenium-webdriver"
  gem "test-recorder", path: "../../"
  gem "activesupport-testing-metadata"
  gem "rspec-rails"
  gem "rspec-retry"
end
